### PR TITLE
putting notes in the margin, see PerseusDL/tei-conversion-tools#36

### PR DESCRIPTION
**Pull request by balmas**
@lcerrato is this okay with you?

### CODE REVIEW

**Comment by lcerrato** [comment]
Looks like the note is at the bottom of the column on the page. Why would it be set to the margin in this case? Smith's does not appear to have marginalia.
Not able to view the structure of this work in depth at this time — I don't have this checked out at the moment and the work is too large to diff — but the other possibility would be the end of the specific entry in question.
I do not know if "end" would accomplish this based on the proposed structure.

**Comment by lcerrato** [comment]
I will checkout and follow up asap (if desired). 
No reason not to temp assign to "margin," but trying to understand the reason in this case.

**Comment by balmas** [comment]
No urgency -- I just didn't want to lose this change, which I made in order to be able to produce static displays of Smiths for https://github.com/perseids-project/perseids_docs/issues/295

It was mainly my own ignorance in using margin. But this does raise an interesting discussion, although maybe less so for notes, which I guess we still hope to pull out notes into separate indices.  The question is whether, when encoding/optimizing for CTS, do we obey the same rules as to markup that only has meaning in the context of adhering to the original print copy?

**Comment by lcerrato** [comment]
If you want to be sure the note is with a particular entry, then I could see "bottom" might not be the best choice depending on the CTS optimization.
But when looking at Perseus print copies, it's usually on the bottom of the page or the bottom opposite.
"inline" may be the better default for this type of work.

**Pull request merged**
